#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/xRegistry.Types.AzureFunctions/ && \
    dotnet build src/xRegistry.Types.AzureFunctions/ && \
    echo "Now, run the following to start the project: func start"
